version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: es
    healthcheck:
      test: ["CMD", "curl", "-f", "es:9200/"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    # image: foodtrucks-web
    build: .
    command: python3 app.py
    environment:
    - DEBUG=True
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
